### ISSUE TITLE
Handle UPnP Error 402 (Full routing table)

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [samizdapp/herakles#3]
For users who run a lot of UPnP applications (i.e. video games), it will be common for the UPnP table in their router to be full.

When this happens, a 402 will often be returned.

Handle 402 errors by checking for many UPnP entries (past some threshold?) and removing either some or all of them.

This Perl script deletes multiple entries by iterating over the list and deleting each one individually: https://www.howtoforge.com/administrating-your-gateway-device-via-upnp#igdctlpl

I couldn't find a best practice on this; it is possible that clearing the entire table is the preferred method so that any applications that lose their entries are more likely to recover.

**Comment by JoshuaCWebDeveloper** [comment]
@rynomad @yourpresidentuniversal This is fixed isn't?

**Comment by rynomad** [comment]
yes! closing
