### ISSUE TITLE
Inefficiencies in client connection to box (can take minutes to connect)

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [samizdapp/herakles#59]
Even if the client is able to connect to the box through the LAN, it can sometimes take over a minute for that connection to actually happen (during which, the user will be shown the online message).

This is due to a few observed inefficiencies:
1) libp2p attempts to connect to a bunch of addresses that don't exist rather than attempting to connect to the addresses in the bootstrap list that it is given
2) libp2p connects to the bootstrap addresses in a non-intuitive manner. Connections are attempted on some addresses much more frequently than others, and it can take many minutes for some addresses to even have one connection attempt
3) Old relay addresses are never pruned (#15), which causes libp2p to spend a bunch of time connecting to them (and worsening problem 2) )
4) Relay addresses are prioritized over local addresses. So even if the client is on LAN, it will spend a bunch of time trying to connect to relays before attempting to connect directly to the box.

**Comment by HOGGL** [comment]
When connecting, four relays are added to the libp2p peer store initially.  This grows overtime with the autodial feature. For some reason internal addresses are added as peers, slowing down the connection process until they error out.

On one occasion, there were 13 relays reportedly connected. Of the ~30 addresses in the peer store (18 unique), 3 were valid external IP addresses.

It takes a couple minutes for the autodial to break, taking minutes to do what would normally take seconds. This can only be solved by reinstalling the PWA.

**Comment by JoshuaCWebDeveloper** [comment]
Inefficiency number 1 should be resolved.

**Comment by JoshuaCWebDeveloper** [comment]
Number 1 is _not_ resolved, but has been moved to a separate issue: #86.

**Comment by JoshuaCWebDeveloper** [comment]
The remainder of this issue is fixed by https://github.com/samizdapp/athena/pull/51
