### ISSUE TITLE
Can't connect via Relays

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [samizdapp/herakles#60]
For the past several days, connections from client to box over relays have generally not been working.

#59 Complicates understanding this issue fully.

**Comment by rynomad** [comment]
this should be fixed finally by https://github.com/samizdapp/herakles/pull/67

refactor of sourcing relay logic dropped the `p2p-circuit/....` component from relay advertisements, rendering relays functionally inert.

**Comment by JoshuaCWebDeveloper** [comment]
Fixed by https://github.com/samizdapp/athena/pull/51
